---
- name: check if homebrew is installed
  register: homebrew_path
  stat:
    path: /opt/homebrew

- name: install homebrew
  script: ../install-homebrew.sh
  when: not homebrew_path.stat.exists

- name: add homebrew to PATH
  shell: |
    echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> ~/.zprofile
    eval "$(/opt/homebrew/bin/brew shellenv)"
  when: not homebrew_path.stat.exists

- name: tap homebrew/cask repositories
  community.general.homebrew_tap:
    name:
      - aws/tap
      - homebrew/cask
      - homebrew/cask-versions
    state: present
  tags:
    - up

- name: install homebrew formulae
  community.general.homebrew:
    name:
      - exiftool
      - jq
      - neovim
      - pure
      - volta
      - youtube-dl
      - zsh-autosuggestions
      - zsh-syntax-highlighting
    state: latest
    update_homebrew: true
  tags:
    - up

- name: install homebrew casks
  community.general.homebrew_cask:
    name:
      - 1password
      - 1password-cli
      - appcleaner
      - doxie
      - figma
      - firefox-developer-edition
      - google-chrome
      - grammarly-desktop
      - ngrok
      - postman
      - raycast
      - signal
      - steam
      - visual-studio-code
      - warp
    state: latest
    update_homebrew: true
  tags:
    - up
